# Generated by Django 2.2.12 on 2020-07-01 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverages', models.CharField(choices=[('ac', 'Áreas de Control'), ('ageb', 'Agebs'), ('mun', 'Municipal'), ('statal', 'Estatal')], help_text='Selecciona la covertura de la capa', max_length=10, verbose_name='*Cobertura')),
                ('state', models.CharField(blank=True, help_text='Selecciona el estado', max_length=64, null=True, verbose_name='Estatal')),
                ('mun', models.CharField(blank=True, max_length=64, null=True, verbose_name='Municipal')),
                ('ageb', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ageb')),
                ('ac', models.CharField(blank=True, max_length=64, null=True, verbose_name='Area de control')),
                ('status', models.BooleanField(default=1, verbose_name='Estaus')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('conf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_ca', to='toolkit.ConfigureObjectSOA', verbose_name='Config')),
                ('user_sos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
