# Generated by Django 2.2.16 on 2020-11-13 23:06

from django.db import migrations, models
import django.db.models.deletion
import geonode.base_style.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='rgba(75, 136, 101, 1)', max_length=250, null=True, verbose_name='Color de fondo y del tema')),
                ('color_gestion', models.CharField(default='rgba(52, 99, 72, 1)', max_length=250, null=True, verbose_name='Color de encabezados en gestión')),
                ('color_font', models.CharField(default='rgba(36, 117, 71, 1)', max_length=250, null=True, verbose_name='Color de texto (donde aplique)')),
                ('logo', models.ImageField(blank=True, default=None, help_text='Nota: El logo aparecerá en todos los encabezados', null=True, upload_to=geonode.base_style.models.get_upload_path, verbose_name='Logo')),
                ('title', models.CharField(default='Plataforma Geoweb IDEGeo', max_length=300, null=True, verbose_name='Título o nombre de plataforma')),
                ('subtitle', models.CharField(default='Servicios de Información Geoespacial', max_length=300, null=True, verbose_name='Subntitulo de plataforma')),
                ('cms', models.BooleanField(default=False, verbose_name='Usar CMS como home de plataforma')),
                ('cmsHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content_handler.ManagmentContent', verbose_name='Nombre del CMS')),
            ],
        ),
    ]
