# Generated by Django 2.2.16 on 2020-11-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20200115_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='microsite_access',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene permisos para crear microsiios', verbose_name='microsite access'),
        ),
    ]
