# Generated by Django 2.2.16 on 2020-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_profile_microsite_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ide_access',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso a la gestion de la ide', verbose_name='ide access'),
        ),
    ]
