# Generated by Django 2.2.12 on 2020-07-01 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0027_auto_20170801_1228_squashed_0033_auto_20180606_1543'),
        ('mviewer', '0001_initial'),
        ('maps', '__first__')
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Título')),
                ('description', models.TextField(help_text='Esta descripción saldrá en el tooltip del icono, junto conel título', max_length=250, verbose_name='Descripción')),
                ('constant', models.CharField(help_text='Esta constante no se tiene que repetir por que será el id de tu evento', max_length=40, verbose_name='Constante')),
                ('help', models.CharField(blank=True, help_text='Esta ayuda saldrá en el detalle del visualizador (Esto es en caso de que la herramienta necesite otro tipo de configuración)', max_length=250, null=True, verbose_name='Ayuda')),
                ('status', models.BooleanField(blank=True, verbose_name='Activa')),
                ('icon', models.CharField(help_text='puedes consultar: https://fontawesome.com/v4.7.0/icons/', max_length=250, verbose_name='Ingresa el icono para tu herramienta ej: (trash)')),
                ('general_tool', models.BooleanField(blank=True, help_text='Si tu herramienta va ligada a una capa, no selecciones esta opción', verbose_name='General')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigureObjectSOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.CharField(blank=True, help_text='Este título es el que se mostrará en tu visualizador', max_length=250, null=True, verbose_name='Título')),
                ('status', models.BooleanField(default=1, verbose_name='Activa')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('layer_mv', models.ForeignKey(blank=True, help_text='Selecciona la capa a aplicar la herramienta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_layers_mv', to='mviewer.LayerIds', verbose_name='Capas de mviewer relacionadas')),
                ('layers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_layers', to='layers.Layer', verbose_name='Capas relacionadas')),
                ('maps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_maps', to='maps.Map', verbose_name='Mapas relacionados')),
                ('mviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_mviewer', to='mviewer.MViewer', verbose_name='Vizualizadores relacionados')),
                ('tool', models.ForeignKey(help_text='Selecciona una herramienta de análisis para tu visualizador', on_delete=django.db.models.deletion.CASCADE, related_name='sos_tools', to='toolkit.SpatialObject', verbose_name='Herramientas relacionadas')),
                ('user_sos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
