# Generated by Django 2.2.12 on 2020-06-26 19:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import geonode.blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('format', models.CharField(choices=[('standard', 'Historia'), ('link', 'Enlace')], default='standard', max_length=20)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Entrada')),
                ('image', models.ImageField(blank=True, null=True, upload_to=geonode.blog.models.get_upload_path, verbose_name='Imagen')),
                ('gallery_zip', models.FileField(blank=True, null=True, upload_to='blog/gallery/%Y/%m/%d/')),
                ('fix_index', models.BooleanField(default=False, verbose_name='Destacado en inicio')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tema')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=geonode.blog.models.get_upload_path, verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stack_order', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('blog_active', models.BooleanField(default=True, verbose_name='Blog')),
                ('menu_active', models.BooleanField(default=True, verbose_name='Menú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Topic', verbose_name='Categoría superior')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=geonode.blog.models.get_upload_path)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Topic', verbose_name='Asociar a una tema'),
        ),
    ]
