# Generated by Django 2.2.16 on 2020-12-08 23:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('icon', fontawesome.fields.IconField(blank=True, default='', max_length=60, verbose_name='Icono')),
                ('custome_icon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Icono Personalizado')),
                ('stack_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mviewer',
            name='custome_zoom',
            field=models.IntegerField(default='4', null=True),
        ),
        migrations.AddField(
            model_name='mviewer',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Información adicional'),
        ),
        migrations.AddField(
            model_name='mviewer',
            name='landing_info',
            field=models.BooleanField(default=False, help_text='Muestra informacion adicional al entrar al panorama', verbose_name='Mostrar informacion adicional'),
        ),
        migrations.AddField(
            model_name='mviewer',
            name='limited_zoom',
            field=models.BooleanField(default=False, help_text='Ajuste el mapa para delimitar el zoom out', verbose_name='Activar para restringir Zoom'),
        ),
        migrations.CreateModel(
            name='TopicTextItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('contents', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('stack_order', models.IntegerField(blank=True, null=True)),
                ('topic_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mviewer.TopicText', verbose_name='Tematica texto')),
            ],
        ),
        migrations.AddField(
            model_name='topictext',
            name='mviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textopics', to='mviewer.MViewer', verbose_name='Visualizador'),
        ),
        migrations.CreateModel(
            name='MviewerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Título del Panorama')),
                ('logo_1', models.ImageField(blank=True, default=None, help_text='Este logo aparecerá en el encabezado del panorama', null=True, upload_to='images/', verbose_name='Logo 1')),
                ('link_1', models.URLField(blank=True, default=None, verbose_name='URL logo 1')),
                ('alt_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título 1')),
                ('logo_2', models.ImageField(blank=True, default=None, help_text='Este logo aparecerá en el encabezado del panorama', null=True, upload_to='images/', verbose_name='Logo 2')),
                ('link_2', models.URLField(blank=True, default=None, verbose_name='URL logo 2')),
                ('alt_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título 2')),
                ('logo_3', models.ImageField(blank=True, default=None, help_text='Este logo aparecerá en el encabezado del panorama', null=True, upload_to='images/', verbose_name='Logo 3')),
                ('link_3', models.URLField(blank=True, default=None, verbose_name='URL logo 3')),
                ('alt_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título 3')),
                ('logo_4', models.ImageField(blank=True, default=None, help_text='Este logo aparecerá en el encabezado del panorama', null=True, upload_to='images/', verbose_name='Logo 4')),
                ('link_4', models.URLField(blank=True, default=None, verbose_name='URL logo 4')),
                ('alt_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título 4')),
                ('logo_5', models.ImageField(blank=True, default=None, help_text='Este logo aparecerá en el encabezado del panorama', null=True, upload_to='images/', verbose_name='Logo 5')),
                ('link_5', models.URLField(blank=True, default=None, verbose_name='URL logo 5')),
                ('alt_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título 5')),
                ('title_color', models.CharField(blank=True, max_length=40, null=True, verbose_name='Color de Texto (Este color se aplicará solamente al texto del encabezado)')),
                ('title_sieze', models.IntegerField(default='28', max_length=250, null=True, verbose_name='Tamaño de fuente (px)')),
                ('title_font', models.CharField(blank=True, choices=[('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Lucida Sans', 'Lucida Sans'), ('HelveticaNeue', 'HelveticaNeue'), ('Arial', 'Arial'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Source Sans Pro', 'Source Sans Pro')], default='Montserrat', max_length=40, null=True, verbose_name='Tipo de letra')),
                ('header_color', models.CharField(blank=True, max_length=40, null=True, verbose_name='Color de Fondo (Este color se aplicará al fondo del encabezado)')),
                ('mviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mviewer.MViewer', verbose_name='Visualizador')),
            ],
        ),
    ]
