# Generated by Django 2.2.12 on 2020-07-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0043_auto_20200527_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CencusConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='Alias')),
                ('name_layer', models.CharField(max_length=250, unique=True, verbose_name='Nombre de la capa')),
                ('coverage', models.CharField(max_length=20, verbose_name='Estados')),
                ('state', models.BooleanField(verbose_name='Estatus')),
                ('all_states', models.BooleanField(verbose_name='Todos los estados')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CensusLayer',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('custom_table', models.CharField(blank=True, max_length=128, null=True)),
                ('workspace', models.CharField(max_length=128)),
                ('store', models.CharField(max_length=128)),
                ('storeType', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('typename', models.CharField(blank=True, max_length=128, null=True)),
                ('charset', models.CharField(default='UTF-8', max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.resourcebase',),
        ),
    ]
